src/components/common/InputForm.tsx
src/pages/InputFormTest.tsx

공용 인풋 폼 컴포넌트 다른 모든 input 어트리뷰트 props로 받을 수 있도록 했습니다.

96 공용 input 모든 어트리뷰트 받을 수 있도록 수정

---

src/main.tsx
src/pages/Footer.tsx
src/pages/Notfound.tsx

feat: add NotFound page

---

src/components/EditPw/EditPwButton.tsx
src/components/EditPw/EmailInput.tsx
src/components/EditPw/NameInput.tsx
src/layouts/CenterPageLayout.tsx
src/main.tsx
src/pages/EditPwPage.tsx
src/pages/LoginPage.tsx
src/stores/editPwStore.ts

비밀번호 변경 페이지 추가합니다.

---

package.json
pnpm-lock.yaml
src/apis/authApis.ts
src/apis/index.ts
src/components/login/EmailInput.tsx
src/components/login/LoginButton.tsx
src/components/login/LoginForm.tsx
src/components/login/index.ts
src/pages/LoginPage.tsx
src/react-queries/queryKeys.ts
src/react-queries/useSignIn.ts
src/supabase/index.ts
src/tests/login.test.tsx

- supabase 사용해서 로그인 가능하도록 했습니다.
- react query와 함께 사용해서 로딩, 에러, 성공 상태 관리 쉽게 할 수 있도록 구현 했습니다.
- 이메일, 패스워드가 유효하지 않으면 로그인 되지 않도록 했습니다.
반환되는 access 토큰은 로컬스토리지에 자동 저장되고 요청 전송시 자동으로 함께 전송 됩니다.
**Email**: test@test.com
**Password**: testtest

21 로그인 버튼을 클릭시 로그인 할 수 있어야 한다

---

src/components/Join/JoinButton.tsx
src/components/Join/NickNameInput.tsx
src/utils/authUtils.ts

닉네임 필수(2~12자 이상)으로 유효성 검사 추가하였습니다!

fix: 닉네임 관련 유효성 검사 추가

---

src/apis/sessionApis.ts
src/main.tsx
src/providers/ProtectedRoute.tsx
src/react-queries/queryKeys.ts
src/react-queries/useGetSession.ts

- 로그인 되어있지 않다면 로그인 페이지로 리디렉션
- main.tsx파일에서 각 route 요소를 ProtectedRoute로 감싸주기만 하면 사용할 수 있음

feat: 권한 없을시 리디렉션 시키는 프로텍터 추가

---

pnpm-lock.yaml
src/App.tsx
src/styles/index.css

프로토타입의 우측에 위치한 일정관련 레이아웃이 추가되면 사이드바 & 달력 컴포넌트 위치를 재조정해야합니다.
우선적으로 위치만 맞추어두었고 추후 메인 페이지 레이아웃이 완성되면 다시 재조정 진행하겠습니다!

17 sidebar

---

src/styles/index.css
src/supabase/supabse.types.ts

슈파베이스 테이블 타입이랑 로컬에 있는 supabse 타입이랑 일치하지 않아서 해당 문제 수정했습니다.

슈파베이스 데이터베이스와 타입 동기화

---

src/apis/personalScheduleApi.ts
src/components/MyCalendar/CreateEventButton.tsx
src/components/common/Calendar.tsx
src/stores/myEventsStore.ts
src/styles/index.css
src/utils/index.ts

* 캘린더에 개인 일정을 불러오도록 구현
* 일정을 추가하면 DB에 저장하도록 구현
https://github.com/imaginer-dev/DateLeaf/assets/35310404/7cd30e3e-fe87-4425-801f-dbce6ac41363

새 개인 일정을 DB에 추가하고, 캘린더에 불러와서 보여줌

---

src/components/GroupForm/GroupForm.tsx
src/components/common/UserInvite.tsx
src/components/common/UserInviteDialog.tsx
src/components/common/UserInviteList.tsx
src/main.tsx
src/pages/AddGroupSchedulePage.tsx

51 그룹일정 추가 시 db 저장

---

src/App.tsx
src/components/common/Calendar.tsx
src/utils/dateUtils.ts

2024-05-16T00:00:00+00:00~2024-05-23T00:00:00+00:00  데이터 날짜 공통함수 추가
1) formatDateRange
- 만약 시작과 종료날짜가 같으면 2024-05-16
- 시작과 종료날짜가 다르면 2024-05-16~2024-05-23
2) formatTime
- 오전 9시이면 오전9:00

73    날짜 및 시간 포맷

---

src/apis/updateUserApi.ts
src/assets/svgs/ProfileIcon.tsx
src/pages/ProfilePage.tsx
src/react-queries/useUpdateUserPassword.ts
src/styles/index.css

1. 프로필 메인 UI 
2. 프로필 수정 
- 취소시 원래 데이터로 돌아오기
- 닉네임 수정시 수정된 닉네임 노출
- (예정) 프로필 이미지 업로드 
- (예정) 프로필 이미지 최적화
https://github.com/imaginer-dev/DateLeaf/assets/46205870/4583ab87-3799-4fd5-a8fc-8ba8a6baa4b9

164   UI 프로필 수정 구현

---

src/apis/updateUserApi.ts
src/assets/svgs/ProfileIcon.tsx
src/components/common/SideBar/SideBarProfile.tsx
src/hooks/useAddGroupSchedule.ts

feat: supabase storage 로 이미지 업로드 기능 추가

---

src/components/MyCalendar/CreateEventButton.tsx
src/components/common/Calendar.tsx
src/pages/GroupSchedulePage.tsx
src/pages/MyCalendarPage.tsx

일정 수정 버튼 안예쁜거 기존 디자인대로 바꾸어두었고,
개인 일정 수정 삭제시 개인일정 화면으로 이동하게끔 해주었습니다.

개인 일정 추가&수정 성공시 화면 업데이트

---

src/components/common/Calendar.tsx
src/pages/MyCalendarPage.tsx
src/stores/myEventsStore.ts

렌더링 시 배열 초기화 하고 사용하게끔 수정해주었습니다.

fix: 일정 렌더링 시 init 안되는 것 수정

---

src/pages/MyCalendarPage.tsx

fix: useEffect dependency error

---

src/components/common/Calendar.tsx
src/hooks/useAddGroupSchedule.ts
src/pages/AddGroupPage.tsx
src/pages/EditGroupPage.tsx
src/react-queries/useUpdateGroup.ts
src/utils/groupScheduleUtils.ts
src/utils/stringUtils.ts

- 그룹 생성 수정에 유효성 검증 버튼 클릭시에는 검증이 안되고 있었는데 해당 부분 수정했습니다.
- 캘린더 이벤트 UI 텍스트 길어지면 overflow 되던 문제 clamp 사용해서 해결했습니다.

30 유효성 검사 및 캘린더 이벤트 스타일 수정

---

src/components/common/Calendar.tsx

그룹 캘린더에는 일정 카드가 보이지 않도록 수정햇습니다.

feat: 그룹 캘린더에는 일정 카드가 보이지 않도록 수정

---

src/components/MyCalendar/CreateEventButton.tsx
src/components/common/Dialog.tsx
src/utils/dateUtils.ts

- 일정 수정시, 시작날짜/ 끝날짜 디폴트 값 추가 
https://github.com/imaginer-dev/DateLeaf/assets/46205870/4669b663-d5cd-4202-a168-155e73846d45

feat: [UI개선] 일정 수정시 시작일, 끝날짜 디폴트 넣기 및 버튼UI 수정

---

src/components/common/AppBar.tsx

202 UI  UI개선] 일정수정 팝업

---

src/pages/JoinPage.tsx
src/pages/LoginPage.tsx
src/pages/ResetPwPage.tsx

feat: footer가 우선적으로 필요한 페이지 설정

---

package.json
pnpm-lock.yaml
src/components/common/AppBar.tsx

- `@vitejs/plugin-react-swc`, `vite`, `vite-tsconfig-paths` : 빌드 도구와 개발 환경 설정에 관련된 패키지들은 devDependencies 에 위치시켰습니다.
- `"setup": "link:"` : 추후 다른 레포 확장시 모노레포 vs 멀티레포에 대한 의견 조율 후 설정이 필요하다고 생각했습니다.
Closes #218

chore: package.json 의존성 재설정
